const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Create Schema
const EventSchema = new Schema({
  eventId: {
    type: String,
    required: true,
    unique: true,
    // Description: The autogenerated unique identifier for the event (required)
  },
  fridgeItemId: {
    type: Number,
    required: true,
    // Description: The identifier for the food item associated with the event (required)
  },
  description: {
    type: String,
    default: "",
    // Description: Additional description or note for the event (optional)
  },
});

module.exports = mongoose.model("event", EventSchema, "event");
