const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Create Schema
const UserSchema = new Schema({
  listId: {
    type: Number,
    // Description: The autogenerated unique identifier for the list
  },
  userId: {
    type: Number,
    required: true,
    // Description: The unique identifier for the user associated with the list (required)
  }
});

module.exports = list = mongoose.model("lists", UserSchema, "lists");
