const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Create Schema
const UserSchema = new Schema({
  userSettingsId: {
    type: Number,
    // Description: The autogenerated unique identifier for the userSettings
  },
  userId: {
    type: Number,
    required: true,
    // Description: The unique identifier for the user (required)
  },
  daysLeft: {
    type: Number,
    required: true,
    default: 3,
    // Description: The number of days the user wants to be notified before a food's expiration date (required, default: 3)
  },
  isLightMode: {
    type: Boolean,
    required: true,
    default: true,
    // Description: Indicates whether the user prefers a light mode for the application (required, default: true)
  }
});

module.exports = list = mongoose.model("user_settings", UserSchema, "user_settings");
