const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Create Schema
const UserSchema = new Schema({
  userId: {
    type: Number,
    // Description: The autogenerated unique identifier for the User
  },
  firstName: {
    type: String,
    required: true,
    // Description: The first name of the user (required)
  },
  lastName: {
    type: String,
    required: true,
    // Description: The last name of the user (required)
  },
  login: {
    type: String,
    required: true,
    // Description: The user's login username (required)
  },
  password: {
    type: String,
    required: true,
    // Description: The user's password (required)
  },
  email: {
    type: String,
    required: true,
    // Description: The user's email address (required)
  },
  phone: {
    type: String,
    required: true,
    // Description: The user's phone number (required)
  }
});

module.exports = user = mongoose.model("users", UserSchema, "users");
